DotNetCoreMVCProject_CE056/OnlineMovieBuyingRentingSystem/OnlineMovieBuyingRentingSystem/Models/MovieImage.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineMovieBuyingRentingSystem.Models
{
    public class MovieImage
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Please Select Movie")] 
        public int MovieId { get; set; }
        public Movie Movie { get; set; }

        public string Path { get; set; }
        [NotMapped]
        public IFormFile ImageFile { get; set; }
    }
}

DotNetCoreMVCProject_CE056/OnlineMovieBuyingRentingSystem/OnlineMovieBuyingRentingSystem/Controllers/MovieImageController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlineMovieBuyingRentingSystem.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineMovieBuyingRentingSystem.Controllers
{
    public class MovieImageController : Controller
    {
        private readonly IMovieImageRepository _movieimageRepo;
        private readonly IMovieRepository _movieRepo;
        private readonly IWebHostEnvironment _env;
        public MovieImageController(IMovieImageRepository movieimageRepo, IMovieRepository movieRepo, IWebHostEnvironment env)
        {
            this._movieimageRepo = movieimageRepo;
            this._env = env;
            this._movieRepo = movieRepo;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ViewResult Create()
        {
            var movies = _movieimageRepo.GetMovies();
            ViewData["MovieId"] = new SelectList(movies, "Id", "Title");
            return View();
        }

        public IActionResult MovieImages(int Id)
        {
            var movie = _movieRepo.GetMovie(Id);
            ViewBag.Movie = movie;
            var model = _movieimageRepo.GetMovieImages(Id);
            IEnumerable<MovieImage> movieimages = _movieimageRepo.GetMovieImages(Id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(MovieImage movieimage)
        {
            if (ModelState.IsValid)
            {
                string wwwrootpath = _env.WebRootPath;
                string filename = Path.GetFileNameWithoutExtension(movieimage.ImageFile.FileName);
                string extension = Path.GetExtension(movieimage.ImageFile.FileName);
                string Image = filename + extension;
                string path = Path.Combine(wwwrootpath + "/Images/Movies/", Image);
                movieimage.Path = "/Images/Movies/" + Image;
                using (var filestream = new FileStream(path, FileMode.Create))
                {
                    await movieimage.ImageFile.CopyToAsync(filestream);
                }
                MovieImage newmovieimage = _movieimageRepo.AddMovieImage(movieimage);
                return RedirectToAction("details", new { id = newmovieimage.Id });
            }
            return View();
        }
        public ViewResult Details(int Id)
        {
            MovieImage movieimage = _movieimageRepo.GetImage(Id);
            var movies = _movieimageRepo.GetMovies();
            ViewData["MovieId"] = new SelectList(movies, "Id", "Title");
            if (movieimage == null)
            {
                Response.StatusCode = 404;
                return View("MovieImageNotFound", Id);
            }
            return View(movieimage);
        }
        [HttpGet]
        public IActionResult Delete(int Id)
        {
            MovieImage movieimage = _movieimageRepo.GetImage(Id);
            if (movieimage == null)
            {
                return NotFound();
            }
            return View(movieimage);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int Id)
        {
            var movieimage = _movieimageRepo.GetImage(Id);
            _movieimageRepo.DeleteMovieImage(movieimage.Id);

            return RedirectToAction("index");
        }
    }
}

DotNetCoreMVCProject_CE056/OnlineMovieBuyingRentingSystem/OnlineMovieBuyingRentingSystem/Views/MovieImage/Create.cshtml
@model OnlineMovieBuyingRentingSystem.Models.MovieImage

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MovieImage</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MovieId" class="control-label"></label>
                <select asp-for="MovieId" class ="form-control" asp-items="ViewBag.MovieId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Path" class="control-label"></label>
                <input type="file" name="ImageFile" />
                @*<input asp-for="Path" class="form-control" />*@
                <span asp-validation-for="Path" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DotNetCoreMVCProject_CE056/OnlineMovieBuyingRentingSystem/OnlineMovieBuyingRentingSystem/Views/MovieImage/Delete.cshtml
@model OnlineMovieBuyingRentingSystem.Models.MovieImage

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MovieImage</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie.Description)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Path)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Path)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DotNetCoreMVCProject_CE056/OnlineMovieBuyingRentingSystem/OnlineMovieBuyingRentingSystem/Views/MovieImage/Details.cshtml
@model OnlineMovieBuyingRentingSystem.Models.MovieImage

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MovieImage</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Path)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Path)
        </dd>
    </dl>
</div>
<div>
    @*<a href="">Back to Movies</a>*@
    <a asp-controller="MovieImage" asp-action="MovieImages" asp-route-id=@(Model.Movie.Id)>Back to List</a>
</div>

DotNetCoreMVCProject_CE056/OnlineMovieBuyingRentingSystem/OnlineMovieBuyingRentingSystem/Views/MovieImage/MovieImages.cshtml
@model IEnumerable<OnlineMovieBuyingRentingSystem.Models.MovieImage>
@{
    ViewData["Title"] = "MovieImages";
}

<h1>@ViewBag.Movie.Title Images</h1>
@*<h1>MovieImages</h1>*@

<a href="/Admin">Admin</a>
<br />

<a href="/Movie">Manage Movies</a>

<p>
    <a href="/MovieImage/Create">Add New</a>
</p>

<table class="table">
    <thead>
        <tr>
            @*<th>
                    @Html.DisplayNameFor(model => model.Movie)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Movie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Path)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*<td>
                        @Html.DisplayFor(modelItem => item.Movie.Title)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Movie.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Path)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>