DotNetCoreMVCProject_CE056/OnlineMovieBuyingRentingSystem/OnlineMovieBuyingRentingSystem/Models/WebSeriesImage.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineMovieBuyingRentingSystem.Models
{
    public class WebSeriesImage
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Please Select WebSeries")]
        public int WebSeriesId { get; set; }
        public WebSeries WebSeries { get; set; }

        public string Path { get; set; }
        [NotMapped]
        public IFormFile WebSeriesImageFile { get; set; }
    }
}

DotNetCoreMVCProject_CE056/OnlineMovieBuyingRentingSystem/OnlineMovieBuyingRentingSystem/Controllers/WebSeriesImageController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlineMovieBuyingRentingSystem.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineMovieBuyingRentingSystem.Controllers
{
    public class WebSeriesImageController : Controller
    {
        private readonly IWebSeriesImageRepository _webseriesimageRepo;
        private readonly IWebSeriesRepository _webseriesRepo;
        private readonly IWebHostEnvironment _env;
        public WebSeriesImageController(IWebSeriesImageRepository webseriesimageRepo, IWebSeriesRepository webseriesRepo, IWebHostEnvironment env)
        {
            this._webseriesimageRepo = webseriesimageRepo;
            this._env = env;
            this._webseriesRepo = webseriesRepo;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ViewResult Create()
        {
            var webseriess = _webseriesimageRepo.GetWebSeriess();
            ViewData["WebSeriesId"] = new SelectList(webseriess, "Id", "Title");
            return View();
        }

        public IActionResult WebSeriesImages(int Id)
        {
            var webseries = _webseriesRepo.GetWebSeries(Id);
            ViewBag.WebSeries = webseries;
            var model = _webseriesimageRepo.GetWebSeriesImages(Id);
            //IEnumerable<MovieImage> movieimages = _webseriesimageRepo.GetImages(Id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(WebSeriesImage webseriesimage)
        {
            if (ModelState.IsValid)
            {
                string wwwrootpath = _env.WebRootPath;
                string filename = Path.GetFileNameWithoutExtension(webseriesimage.WebSeriesImageFile.FileName);
                string extension = Path.GetExtension(webseriesimage.WebSeriesImageFile.FileName);
                string Image = filename + extension;
                string path = Path.Combine(wwwrootpath + "/Images/WebSeriess/", Image);
                webseriesimage.Path = "/Images/WebSeriess/" + Image;
                using (var filestream = new FileStream(path, FileMode.Create))
                {
                    await webseriesimage.WebSeriesImageFile.CopyToAsync(filestream);
                }
                WebSeriesImage newwebseriesimage = _webseriesimageRepo.AddWebSeriesImage(webseriesimage);
                return RedirectToAction("details", new { id = newwebseriesimage.Id });
            }
            return View();
        }
        public ViewResult Details(int Id)
        {
            WebSeriesImage webseriesimage = _webseriesimageRepo.GetImage(Id);
            var webseriess = _webseriesimageRepo.GetWebSeriess();
            ViewData["WebSeriesId"] = new SelectList(webseriess, "Id", "Title");
            if (webseriesimage == null)
            {
                Response.StatusCode = 404;
                return View("WebSeriesImageNotFound", Id);
            }
            return View(webseriesimage);
        }
        [HttpGet]
        public IActionResult Delete(int Id)
        {
            WebSeriesImage webseriesimage = _webseriesimageRepo.GetImage(Id);
            if (webseriesimage == null)
            {
                return NotFound();
            }
            return View(webseriesimage);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int Id)
        {
            var webseriesimage = _webseriesimageRepo.GetImage(Id);
            _webseriesimageRepo.DeleteWebSeriesImage(webseriesimage.Id);

            return RedirectToAction("index");
        }
    }
}

DotNetCoreMVCProject_CE056/OnlineMovieBuyingRentingSystem/OnlineMovieBuyingRentingSystem/Views/WebSeriesImage/Create.cshtml
@model OnlineMovieBuyingRentingSystem.Models.WebSeriesImage

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>WebSeriesImage</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="WebSeriesId" class="control-label"></label>
                <select asp-for="WebSeriesId" class ="form-control" asp-items="ViewBag.WebSeriesId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Path" class="control-label"></label>
                <input type="file" name="WebSeriesImageFile" />
                @*<input asp-for="Path" class="form-control" />*@
                <span asp-validation-for="Path" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DotNetCoreMVCProject_CE056/OnlineMovieBuyingRentingSystem/OnlineMovieBuyingRentingSystem/Views/WebSeriesImage/Delete.cshtml
@model OnlineMovieBuyingRentingSystem.Models.WebSeriesImage

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WebSeriesImage</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WebSeries)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WebSeries.Description)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Path)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Path)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DotNetCoreMVCProject_CE056/OnlineMovieBuyingRentingSystem/OnlineMovieBuyingRentingSystem/Views/WebSeriesImage/Details.cshtml
@model OnlineMovieBuyingRentingSystem.Models.WebSeriesImage

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>WebSeriesImage</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WebSeries)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WebSeries.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Path)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Path)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="WebSeriesImage" asp-action="WebSeriesImages" asp-route-id=@(Model.WebSeries.Id)>Back to List</a>
</div>

DotNetCoreMVCProject_CE056/OnlineMovieBuyingRentingSystem/OnlineMovieBuyingRentingSystem/Views/WebSeriesImage/WebSeriesImages.cshtml
@model IEnumerable<OnlineMovieBuyingRentingSystem.Models.WebSeriesImage>
@{
    ViewData["Title"] = "WebSeriesImages";
}


<h1>@ViewBag.WebSeries.Title Images</h1>

<a href="/Admin">Admin</a>
<br />

<a href="/WebSeries">Manage WebSeries</a>

<p>
    <a href="/WebSeriesImage/Create">Add New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.WebSeries)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Path)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.WebSeries.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Path)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>